a = int(input("enter the first number"))
b = int(input("enter the second number"))
c = int(input("enter the third number"))
d = int(input("enter the fourth number"))
e = complex(a,b)
f = complex(c,d)
print("addition",e+f)
print("substraction",e-f)
print("divison",e/f)
print("multiplication",e*f)
